name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - v2

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SAHIBDSV_WEBSITE }}'
          channelId: live
          projectId: sahibdsv-website
          target: v2
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
